-- Create a dedicated workouts table so workout history no longer depends on
-- a single JSON blob inside profiles.data.
--
-- This migration is intentionally additive:
-- - existing profile/schedule sync keeps working
-- - no existing data is deleted
-- - the app can be moved to dual-write in a later step

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.workouts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  client_workout_id text not null,
  program text,
  type text not null,
  subtype text,
  performed_at timestamptz not null,
  payload jsonb not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  deleted_at timestamptz
);

create unique index if not exists workouts_user_client_workout_id_key
  on public.workouts (user_id, client_workout_id);

create index if not exists workouts_user_performed_at_idx
  on public.workouts (user_id, performed_at desc);

create index if not exists workouts_user_active_idx
  on public.workouts (user_id, deleted_at, performed_at desc);

drop trigger if exists workouts_set_updated_at on public.workouts;
create trigger workouts_set_updated_at
before update on public.workouts
for each row
execute function public.set_updated_at();

alter table public.workouts enable row level security;

drop policy if exists "Users can read own workouts" on public.workouts;
create policy "Users can read own workouts"
on public.workouts
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own workouts" on public.workouts;
create policy "Users can insert own workouts"
on public.workouts
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update own workouts" on public.workouts;
create policy "Users can update own workouts"
on public.workouts
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own workouts" on public.workouts;
create policy "Users can delete own workouts"
on public.workouts
for delete
using (auth.uid() = user_id);

comment on table public.workouts is
  'Dedicated workout history table. payload stores the full client workout object during the migration away from profiles.data.workouts.';

comment on column public.workouts.client_workout_id is
  'Stable workout id generated by the client and unique per user.';

comment on column public.workouts.performed_at is
  'Workout timestamp from the client record, used for ordering and sync.';

comment on column public.workouts.payload is
  'Full workout JSON object as stored by the client during the transition period.';
